library(data.table)
library(rJava)#https://www.r-statistics.com/2012/08/how-to-load-the-rjava-package-after-the-error-java_home-cannot-be-determined-from-the-registry/
library(xlsx)
# download.file(url = "http://biogeo.ucdavis.edu/data/gadm2.8/rds/FRA_adm1.rds",destfile = "departements.rds")
library(RDS)
library(sp)
library(stringi)
library(dplyr)
library(leaflet)
indicateurs=read.xlsx("../data/Indicateurs_VQS_Dep.xlsx",sheetIndex = 1)
load("../data/FR_gadm.RData")
indicateurs$DÃ.aprtements.=as.character(indicateurs$DÃ.aprtements.)
indicateurs=indicateurs[!is.na(indicateurs$DÃ.aprtements.),]
indicateurs[stri_length(indicateurs$DÃ.aprtements.)==1,]$DÃ.aprtements.=paste0("0",indicateurs[stri_length(indicateurs$DÃ.aprtements.)==1,]$DÃ.aprtements.)
FRA_dep@data=merge(FRA_dep@data,indicateurs,by.x="CCA_2",by.y="DÃ.aprtements.")
FRA_dep_10pct@data=merge(FRA_dep_10pct@data,indicateurs,by.x="CCA_2",by.y="DÃ.aprtements.")
FRA_dep_1pct@data=merge(FRA_dep_1pct@data,indicateurs,by.x="CCA_2",by.y="DÃ.aprtements.")
FRA_dep_list=list("pct100"=FRA_dep,"pct10"=FRA_dep_10pct,"pct1"=FRA_dep_1pct)
